name: Hello World Action

# Trigger the workflow on push and pull request events
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the job that will run on the GitHub runner
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Run Python script
      run: python hello.py
